<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>5.6</VersionPrefix>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- IDE0028: Simplify collection initialization -->
    <!-- IDE0130: Namespace does not match folder structure -->
    <!-- IDE0305: Simplify collection initialization -->
    <!-- IDE0306: Simplify collection initialization -->
    <NoWarn>IDE0028;IDE0130;IDE0305;IDE0306</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <IsAotCompatible>True</IsAotCompatible>
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Value Collections</Title>
    <Authors>Joyless</Authors>
    <Description>A set of collections implemented as ref struct to minimize heap allocations.</Description>
    <PackageProjectUrl>https://github.com/Joy-less/ValueCollections</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Joy-less/ValueCollections</RepositoryUrl>
    <PackageTags>collection;list;value list;ref struct;span;array pool;hash set;dictionary</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.7" />
  </ItemGroup>
</Project>